const SUPABASE_URL='https://weaxqjesqtkkvodwnttx.supabase.co';
const SUPABASE_KEY='sb_publishable_x4p8fV11-JMp0C5W44OKrQ_3Ug_kJw8';
const sb=globalThis.supabase.createClient(SUPABASE_URL,SUPABASE_KEY);
let user,profile,campaign,role,scene,tokens=[],fogs=[],assets=[],roster=[],initiative=[],permissions={},allPermissions=[],dicePool={},channel,tool='select',selected=null,drag=null,panDrag=null,permissionTarget=null,libraryFilter='token',cam={x:0,y:0,z:.65};
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const msg=t=>$('#authMsg').textContent=t;
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
async function boot(){const {data:{session}}=await sb.auth.getSession();if(session)await enter(session.user);sb.auth.onAuthStateChange(async(_,s)=>{if(s&&!user)await enter(s.user);if(!s){user=null;document.body.classList.remove('campaign-mode','master','player','spectator');$('#app').classList.add('hidden');$('#auth').classList.remove('hidden')}})}
async function enter(u){user=u;let {data}=await sb.from('profiles').select('*').eq('id',u.id).single();profile=data;$('#who').textContent=profile?.display_name||profile?.username||'Usuário';$('#auth').classList.add('hidden');$('#app').classList.remove('hidden');show('home')}
function normalizedUsername(){return $('#username').value.trim().toLowerCase()}function internalEmail(username){return `${username}@users.umbravtt.com`}function validUsername(username){return /^[a-z0-9_]{3,24}$/.test(username)}
let signupMode=false;
$('#loginBtn').onclick=async()=>{if(signupMode){signupMode=false;$('#confirmPassword').classList.add('hidden');$('#signupBtn').textContent='Criar conta';msg('');return}const username=normalizedUsername(),password=$('#password').value;if(!validUsername(username))return msg('Usuário inválido. Use 3–24 caracteres: letras, números e _.');if(!password)return msg('Digite sua senha.');$('#loginBtn').disabled=true;const {error}=await sb.auth.signInWithPassword({email:internalEmail(username),password});$('#loginBtn').disabled=false;msg(error?'Usuário ou senha incorretos.':'')};
$('#signupBtn').onclick=async()=>{if(!signupMode){signupMode=true;$('#confirmPassword').classList.remove('hidden');$('#signupBtn').textContent='Confirmar cadastro';msg('Escolha seu usuário e confirme a senha.');return}const username=normalizedUsername(),password=$('#password').value,confirm=$('#confirmPassword').value;if(!validUsername(username))return msg('Use 3–24 caracteres: letras minúsculas, números e _.');if(password.length<6)return msg('A senha precisa ter pelo menos 6 caracteres.');if(password!==confirm)return msg('As senhas não coincidem.');$('#signupBtn').disabled=true;try{const res=await fetch(`${SUPABASE_URL}/functions/v1/signup-username`,{method:'POST',headers:{'Content-Type':'application/json','apikey':SUPABASE_KEY},body:JSON.stringify({username,password})});const data=await res.json().catch(()=>({}));if(!res.ok)return msg(data.message||'Não foi possível criar a conta.');const {error}=await sb.auth.signInWithPassword({email:internalEmail(username),password});msg(error?'Conta criada. Tente entrar com seu usuário e senha.':'')}catch{msg('Falha de conexão ao criar a conta.')}finally{$('#signupBtn').disabled=false}};
$('#logoutBtn').onclick=()=>sb.auth.signOut();$$('header nav button').forEach(b=>b.onclick=()=>show(b.dataset.page));
function show(p){if(p!=='tabletop')document.body.classList.remove('campaign-mode');$$('.page').forEach(x=>x.classList.add('hidden'));$('#'+p).classList.remove('hidden');if(p==='campaigns')loadCampaigns();if(p==='sheets')loadSheets()}
$('#newCampaign').onclick=async()=>{let name=prompt('Nome da campanha:');if(!name)return;let {error}=await sb.rpc('create_campaign',{p_name:name,p_description:''});if(error)alert(error.message);else loadCampaigns()};
async function signed(path){if(!path)return '';let {data}=await sb.storage.from('umbra-assets').createSignedUrl(path,3600);return data?.signedUrl||''}async function campaignCoverUrl(c){return c?.cover_path?await signed(c.cover_path):''}
async function loadCampaigns(){let {data}=await sb.from('campaigns').select('*').order('updated_at',{ascending:false});let {data:mem}=await sb.from('campaign_members').select('*');let list=$('#campaignList');list.innerHTML='';for(const c of data||[]){let r=c.owner_id===user.id?'master':mem?.find(m=>m.campaign_id===c.id&&m.user_id===user.id)?.role||'player',cover=await campaignCoverUrl(c),article=document.createElement('article');article.className='campaignCard';article.innerHTML=`<div class="campaignCardCover"${cover?` style="background-image:linear-gradient(#0002,#0005),url('${cover}')"`:''}></div><div class="campaignCardBody"><h3>${esc(c.name)}</h3><p>${esc(c.description||'Sem descrição')}</p><div class="campaignCardFooter"><small>${c.is_open?'🟢 Sessão aberta':'⚫ Sessão fechada'} · ${r}</small><button>${c.is_open||r==='master'?'Abrir':'Ver campanha'}</button></div></div>`;article.querySelector('button').onclick=()=>openCampaign(c.id,r);list.append(article)}if(!list.children.length)list.innerHTML='<p>Nenhuma campanha ainda.</p>'}
$('#joinBtn').onclick=async()=>{let code=$('#inviteCode').value.trim();let {error}=await sb.rpc('request_campaign_join',{p_code:code,p_role:$('#joinRole').value});alert(error?error.message:'Pedido enviado ao mestre.')};
$('#linkSheet').onclick=async()=>{let tok=prompt('Cole o token da ficha Psyque:');if(!tok)return;await sb.from('linked_sheets').insert({user_id:user.id,external_sheet_id:tok,display_name:'Ficha Psyque',status:'pending'});loadSheets()};async function loadSheets(){let {data}=await sb.from('linked_sheets').select('*').order('created_at',{ascending:false});$('#sheetList').innerHTML=(data||[]).map(s=>`<article class="sheetCard"><h3>${esc(s.display_name)}</h3><p>Status: ${esc(s.status)}</p></article>`).join('')||'<p>Nenhuma ficha vinculada.</p>'}
window.openCampaign=async(id,r)=>{let {data:c,error}=await sb.from('campaigns').select('*').eq('id',id).single();if(error||!c)return alert(error?.message||'Campanha não encontrada.');campaign=c;role=r;scene=(await sb.from('scenes').select('*').eq('campaign_id',id).order('sort_order').limit(1).single()).data;document.body.classList.remove('master','player','spectator');document.body.classList.add(role,'campaign-mode');$('#roleBadge').textContent=role;await refreshCampaignIdentity();show('tabletop');document.body.classList.add('campaign-mode');await loadPermissions();await loadWorld();await loadRoster();await loadInitiative();await loadDiceHistory();await connectRealtime();await loadSide();centerCamera()};
$('#backCampaigns').onclick=async()=>{if(channel){await sb.removeChannel(channel);channel=null}document.body.classList.remove('campaign-mode','master','player','spectator');campaign=role=scene=null;show('campaigns')};
async function refreshCampaignIdentity(){if(!campaign)return;$('#campaignName').textContent=campaign.name;$('#campaignSubtitle').textContent=campaign.description||'Virtual Tabletop';let cover=await campaignCoverUrl(campaign),img=$('#campaignTopCover');if(cover){img.src=cover;img.classList.remove('hidden')}else{img.removeAttribute('src');img.classList.add('hidden')}}
async function loadPermissions(){let {data}=await sb.rpc('get_my_campaign_permissions',{p_campaign_id:campaign.id});permissions=data||{};applyPermissions();if(role==='master'){let r=await sb.rpc('get_campaign_permissions',{p_campaign_id:campaign.id});allPermissions=r.data||[]}}
function can(p){return role==='master'||!!permissions[p]}function applyPermissions(){[['.permission-fog','fog'],['.permission-create-tokens','create_tokens'],['.permission-upload-assets','upload_assets'],['.permission-initiative','manage_initiative'],['.permission-time','manage_time']].forEach(([sel,p])=>$$(sel).forEach(x=>x.classList.toggle('permission-denied',!can(p))));$('#rpgTime').disabled=!can('manage_time')}
async function loadWorld(){if(!scene)return;let [t,f,a,tm]=await Promise.all([sb.from('tokens').select('*').eq('scene_id',scene.id),sb.from('fog_regions').select('*').eq('scene_id',scene.id),sb.from('assets').select('*').or(`owner_id.eq.${user.id},campaign_id.eq.${campaign.id}`),sb.rpc('get_campaign_rpg_time',{p_campaign_id:campaign.id})]);tokens=t.data||[];fogs=f.data||[];assets=a.data||[];if(tm.data){$('#rpgTime').value=String(tm.data).slice(0,16);renderTime(tm.data)}$('#toggleSession').textContent=campaign.is_open?'Fechar sessão':'Abrir sessão';render()}
async function render(){let bg=assets.find(a=>a.id===scene?.background_asset_id);$('#map').src=bg?await signed(bg.path):'';$('#fogLayer').innerHTML=fogs.map(f=>`<div class="fog" data-id="${f.id}" style="left:${f.x}px;top:${f.y}px;width:${f.width}px;height:${f.height}px;opacity:${f.opacity}"></div>`).join('');$('#tokenLayer').innerHTML='';for(let t of tokens){let el=document.createElement('div');el.className='token'+(selected===t.id?' selected':'');el.dataset.id=t.id;el.style.cssText=`left:${t.x}px;top:${t.y}px;width:${t.width}px;height:${t.height}px;transform:rotate(${t.rotation||0}deg)`;let a=assets.find(x=>x.id===t.image_asset_id);if(a)el.style.backgroundImage=`url("${await signed(a.path)}")`;else if(t.data?.image)el.style.backgroundImage=`url("${String(t.data.image).replace(/"/g,'')}")`;el.innerHTML=`<span class="name">${esc(t.name)}</span>`;el.onpointerdown=e=>tokenDown(e,t);$('#tokenLayer').append(el)}applyCam();renderAssets()}
function mayMoveToken(t){return role!=='spectator'&&(can('move_any_token')||(t.player_movable&&!t.locked&&t.controller_user_id===user.id&&can('move_own_tokens')))}function tokenDown(e,t){if(tool!=='select'||!mayMoveToken(t))return;e.stopPropagation();selected=t.id;let p=worldPoint(e);drag={id:t.id,dx:p.x-t.x,dy:p.y-t.y};render()}
function worldPoint(e){let r=$('#viewport').getBoundingClientRect();return{x:(e.clientX-r.left-cam.x)/cam.z,y:(e.clientY-r.top-cam.y)/cam.z}}
$('#viewport').onpointermove=e=>{if(panDrag){cam.x=panDrag.cx+e.clientX-panDrag.x;cam.y=panDrag.cy+e.clientY-panDrag.y;applyCam();return}if(e.buttons===2&&channel){let p=worldPoint(e);channel.send({type:'broadcast',event:'cursor',payload:{id:user.id,name:profile?.display_name||profile?.username,x:p.x,y:p.y,show:true}})}if(!drag)return;let t=tokens.find(x=>x.id===drag.id),p=worldPoint(e);t.x=p.x-drag.dx;t.y=p.y-drag.dy;let el=$(`.token[data-id="${t.id}"]`);if(el){el.style.left=t.x+'px';el.style.top=t.y+'px'}channel?.send({type:'broadcast',event:'token_move',payload:{id:t.id,x:t.x,y:t.y}})};
$('#viewport').onpointerup=async e=>{panDrag=null;if(e.button===2)channel?.send({type:'broadcast',event:'cursor',payload:{id:user.id,show:false}});if(drag){let t=tokens.find(x=>x.id===drag.id);drag=null;let {error}=await sb.rpc('update_token_transform',{p_token_id:t.id,p_x:t.x,p_y:t.y,p_width:t.width,p_height:t.height,p_rotation:t.rotation||0});if(error)await loadWorld()}};$('#viewport').oncontextmenu=e=>e.preventDefault();
$('#viewport').onwheel=e=>{e.preventDefault();let r=$('#viewport').getBoundingClientRect(),mx=e.clientX-r.left,my=e.clientY-r.top,wx=(mx-cam.x)/cam.z,wy=(my-cam.y)/cam.z,nz=Math.max(.12,Math.min(2.5,cam.z*(e.deltaY>0?.9:1.1)));cam.x=mx-wx*nz;cam.y=my-wy*nz;cam.z=nz;applyCam()};function applyCam(){$('#world').style.transform=`translate(${cam.x}px,${cam.y}px) scale(${cam.z})`;$('#zoomLabel').textContent=Math.round(cam.z*100)+'%'}function centerCamera(){let v=$('#viewport').getBoundingClientRect(),w=scene?.width||6000,h=scene?.height||4000;cam.z=Math.min(.8,Math.max(.12,Math.min(v.width/w,v.height/h)*1.15));cam.x=(v.width-w*cam.z)/2;cam.y=(v.height-h*cam.z)/2;applyCam()}$('#zoomIn').onclick=()=>{cam.z=Math.min(2.5,cam.z*1.15);applyCam()};$('#zoomOut').onclick=()=>{cam.z=Math.max(.12,cam.z/1.15);applyCam()};$('#centerView').onclick=centerCamera;
$$('[data-tool]').forEach(b=>b.onclick=()=>{tool=b.dataset.tool;$$('[data-tool]').forEach(x=>x.classList.toggle('active',x===b))});
$('#viewport').onpointerdown=e=>{if(e.target.closest('.token'))return;if(tool==='pan'||e.button===1){panDrag={x:e.clientX,y:e.clientY,cx:cam.x,cy:cam.y};return}if((tool==='fog'||tool==='fogOpacity')&&!can('fog'))return;if(tool==='fog'||tool==='fogOpacity'){let start=worldPoint(e),box=$('#selectionBox');box.style.display='block';let move=ev=>{let q=worldPoint(ev),x=Math.min(start.x,q.x),y=Math.min(start.y,q.y),w=Math.abs(q.x-start.x),h=Math.abs(q.y-start.y);Object.assign(box.style,{left:x+'px',top:y+'px',width:w+'px',height:h+'px'})},up=async ev=>{window.removeEventListener('pointermove',move);window.removeEventListener('pointerup',up);box.style.display='none';let q=worldPoint(ev),x=Math.min(start.x,q.x),y=Math.min(start.y,q.y),w=Math.abs(q.x-start.x),h=Math.abs(q.y-start.y);if(w<5||h<5)return;if(tool==='fog'){await sb.rpc('create_fog_region',{p_campaign_id:campaign.id,p_scene_id:scene.id,p_x:x,p_y:y,p_width:w,p_height:h,p_opacity:1})}else{let op=Math.max(0,Math.min(1,Number(prompt('Opacidade de 0 a 100:',50))/100));for(let f of fogs.filter(f=>!(f.x+f.width<x||f.x>x+w||f.y+f.height<y||f.y>y+h)))await sb.rpc('set_fog_opacity',{p_fog_id:f.id,p_opacity:op})}await loadWorld();broadcastRefresh()};window.addEventListener('pointermove',move);window.addEventListener('pointerup',up)}};
async function connectRealtime(){if(channel)await sb.removeChannel(channel);channel=sb.channel('campaign:'+campaign.id,{config:{broadcast:{self:false},presence:{key:user.id}}});channel.on('broadcast',{event:'token_move'},({payload:p})=>{let t=tokens.find(x=>x.id===p.id);if(t){t.x=p.x;t.y=p.y;let el=$(`.token[data-id="${p.id}"]`);if(el){el.style.left=p.x+'px';el.style.top=p.y+'px'}}}).on('broadcast',{event:'cursor'},({payload:p})=>cursor(p)).on('broadcast',{event:'refresh'},async()=>{await Promise.all([loadWorld(),loadRoster(),loadInitiative(),loadDiceHistory()])}).on('broadcast',{event:'campaign_updated'},async()=>{let {data}=await sb.from('campaigns').select('*').eq('id',campaign.id).single();if(data){campaign=data;await refreshCampaignIdentity()}}).on('presence',{event:'sync'},()=>renderRoster()).subscribe(async status=>{if(status==='SUBSCRIBED')await channel.track({user_id:user.id,name:profile?.display_name||profile?.username||'Usuário',role})})}
function broadcastRefresh(){channel?.send({type:'broadcast',event:'refresh',payload:{}})}function cursor(p){let id='c'+p.id,el=document.getElementById(id);if(!p.show){el?.remove();return}if(!el){el=document.createElement('div');el.id=id;el.className='cursorDot';el.innerHTML=`<span>${esc(p.name||'Jogador')}</span>`;$('#cursorLayer').append(el)}el.style.left=p.x+'px';el.style.top=p.y+'px'}
async function loadRoster(){let {data}=await sb.rpc('get_campaign_roster',{p_campaign_id:campaign.id});roster=data||[];renderRoster();if(role==='master'){let p=await sb.rpc('get_campaign_permissions',{p_campaign_id:campaign.id});allPermissions=p.data||[]}}
function renderRoster(){let online=new Set(Object.values(channel?.presenceState()||{}).flat().map(x=>x.user_id));$('#presenceCount').textContent=`${online.size} online`;$('#members').innerHTML=roster.map(m=>`<div class="memberRow ${role==='master'&&m.role!=='master'?'manageable':''}" data-user="${m.user_id}"><div class="memberAvatar">${esc((m.display_name||m.username||'?')[0].toUpperCase())}</div><div class="memberInfo"><b>${esc(m.display_name||m.username||'Usuário')}</b><small>${m.role==='master'?'Mestre':m.role==='spectator'?'Espectador':'Jogador'}</small></div><i class="onlineDot ${online.has(m.user_id)?'online':''}"></i></div>`).join('');if(role==='master')$$('.memberRow.manageable').forEach(el=>el.onclick=()=>openPermissions(el.dataset.user))}
async function openPermissions(uid){permissionTarget=roster.find(x=>x.user_id===uid);if(!permissionTarget)return;$('#permissionPlayerName').textContent=permissionTarget.display_name||permissionTarget.username||'Jogador';$('#permissionRole').value=permissionTarget.role==='spectator'?'spectator':'player';let p=allPermissions.find(x=>x.user_id===uid)||{move_own_tokens:true};$$('[data-perm]').forEach(i=>i.checked=!!p[i.dataset.perm]);$('#permissionsModal').classList.remove('hidden')}
function closePermissions(){$('#permissionsModal').classList.add('hidden');permissionTarget=null}$('#closePermissions').onclick=closePermissions;$$('[data-close-permissions]').forEach(x=>x.onclick=closePermissions);$('#savePermissions').onclick=async()=>{if(!permissionTarget)return;let obj={};$$('[data-perm]').forEach(i=>obj[i.dataset.perm]=i.checked);let a=await sb.rpc('set_member_permissions',{p_campaign_id:campaign.id,p_user_id:permissionTarget.user_id,p_permissions:obj});if(a.error)return alert(a.error.message);let b=await sb.rpc('set_campaign_member_role',{p_campaign_id:campaign.id,p_user_id:permissionTarget.user_id,p_role:$('#permissionRole').value});if(b.error)return alert(b.error.message);closePermissions();await loadRoster();broadcastRefresh()};
async function loadSide(){if(role!=='master'){if($('#requests'))$('#requests').innerHTML='';return}let {data:req}=await sb.from('campaign_join_requests').select('*,profiles!campaign_join_requests_requester_id_fkey(display_name)').eq('campaign_id',campaign.id).eq('status','pending');$('#requests').innerHTML=(req||[]).map(r=>`<div class="request">${esc(r.profiles?.display_name||'Usuário')} quer entrar como ${esc(r.requested_role)}<br><button onclick="resolveReq('${r.id}',true)">Aceitar</button> <button onclick="resolveReq('${r.id}',false)" class="ghost">Recusar</button></div>`).join('')}window.resolveReq=async(id,ok)=>{await sb.rpc('resolve_join_request',{p_request_id:id,p_accept:ok});await loadSide();await loadRoster();broadcastRefresh()};
$('#inviteBtn').onclick=async()=>{let {data,error}=await sb.rpc('create_campaign_invite',{p_campaign_id:campaign.id,p_role:'player'});if(error)return alert(error.message);let link=`${location.origin}${location.pathname}?invite=${encodeURIComponent(data)}`;try{await navigator.clipboard.writeText(link);alert(`Convite copiado!\n${link}`)}catch{prompt('Copie o convite:',link)}};
$('#toggleSession').onclick=async()=>{if(role!=='master')return;let {error}=await sb.rpc('set_campaign_open',{p_campaign_id:campaign.id,p_open:!campaign.is_open});if(error)return alert(error.message);campaign.is_open=!campaign.is_open;$('#toggleSession').textContent=campaign.is_open?'Fechar sessão':'Abrir sessão'};
$$('[data-hub]').forEach(b=>b.onclick=()=>{$$('[data-hub]').forEach(x=>x.classList.toggle('active',x===b));$$('.hubPane').forEach(x=>x.classList.add('hidden'));$('#hub'+b.dataset.hub[0].toUpperCase()+b.dataset.hub.slice(1)).classList.remove('hidden')});
async function loadInitiative(){let {data}=await sb.from('initiative_entries').select('*').eq('campaign_id',campaign.id).eq('scene_id',scene.id).order('initiative',{ascending:false});initiative=data||[];$('#initiative').innerHTML=initiative.map(i=>`<div class="initiativeEntry"><span class="initiativeValue">${esc(i.initiative)}</span><b>${esc(i.name)}</b>${can('manage_initiative')?`<button class="ghost" onclick="deleteInitiative('${i.id}')">✕</button>`:''}</div>`).join('')||'<span class="muted">Nenhuma iniciativa.</span>'}$('#addInitiative').onclick=async()=>{if(!can('manage_initiative'))return;let name=prompt('Nome:');if(!name)return;let value=Number(prompt('Iniciativa:',10));if(!Number.isFinite(value))return;let {error}=await sb.rpc('add_initiative_entry',{p_campaign_id:campaign.id,p_scene_id:scene.id,p_name:name,p_initiative:value});if(error)return alert(error.message);await loadInitiative();broadcastRefresh()};window.deleteInitiative=async id=>{if(!can('manage_initiative'))return;await sb.rpc('delete_initiative_entry',{p_entry_id:id});await loadInitiative();broadcastRefresh()};
function addDie(sides){sides=Number(sides);if(!Number.isInteger(sides)||sides<2||sides>10000)return;dicePool[sides]=(dicePool[sides]||0)+1;renderDicePool()}function renderDicePool(){$$('[data-die]').forEach(b=>b.classList.toggle('hasDice',!!dicePool[b.dataset.die]));let entries=Object.entries(dicePool).filter(([,q])=>q>0);$('#dicePool').innerHTML=entries.length?entries.map(([s,q])=>`<span class="diceChip">${q}d${s}</span>`).join(''):'Nenhum dado selecionado.'}$$('[data-die]').forEach(b=>b.onclick=()=>addDie(b.dataset.die));$('#addCustomDie').onclick=()=>addDie($('#customSides').value);$('#clearDice').onclick=()=>{dicePool={};renderDicePool()};$('#rollDice').onclick=async()=>{let dice=Object.entries(dicePool).filter(([,q])=>q>0).map(([s,q])=>({sides:Number(s),qty:q}));if(!dice.length)return;let {data,error}=await sb.rpc('roll_campaign_dice',{p_campaign_id:campaign.id,p_dice:dice});if(error)return alert(error.message);$('#diceResult').classList.remove('hidden');$('#diceResult').innerHTML=`<small>${esc(data.expression)}</small><strong>${data.result}</strong>`;dicePool={};renderDicePool();await loadDiceHistory();broadcastRefresh()};
async function loadDiceHistory(){let {data}=await sb.rpc('get_campaign_dice_rolls',{p_campaign_id:campaign.id,p_limit:20});$('#diceHistory').innerHTML=(data||[]).map(r=>`<div class="rollHistory"><b>${esc(r.display_name)}: ${r.result}</b><small>${esc(r.expression)}</small></div>`).join('')}
function renderTime(v){let d=new Date(String(v).replace(' ','T'));$('#rpgTimeDisplay').textContent=isNaN(d)?String(v):d.toLocaleString('pt-BR',{dateStyle:'medium',timeStyle:'short'})}$('#saveRpgTime').onclick=async()=>{if(!can('manage_time'))return;let v=$('#rpgTime').value;if(!v)return;let {error}=await sb.rpc('set_rpg_time',{p_campaign_id:campaign.id,p_time:v});if(error)return alert(error.message);renderTime(v);broadcastRefresh()};
$('#addToken').onclick=async()=>{if(!can('create_tokens'))return;let name=prompt('Nome do token:','Novo token');if(!name)return;let {error}=await sb.rpc('create_generic_token',{p_campaign_id:campaign.id,p_scene_id:scene.id,p_name:name,p_controller_user_id:null});if(error)return alert(error.message);await loadWorld();broadcastRefresh()};
$('#addMap').onclick=()=>{if(can('upload_assets')){window.assetKind='map';$('#assetFile').click()}};$('#assetFile').onchange=async e=>{let f=e.target.files[0];if(!f||!can('upload_assets'))return;let path=`${user.id}/${crypto.randomUUID()}-${f.name.replace(/[^a-zA-Z0-9._-]/g,'_')}`;let {error}=await sb.storage.from('umbra-assets').upload(path,f);if(error)return alert(error.message);let {data:a,error:ae}=await sb.from('assets').insert({owner_id:user.id,campaign_id:campaign.id,path,name:f.name,asset_type:window.assetKind||'image',mime_type:f.type,size_bytes:f.size}).select().single();if(ae)return alert(ae.message);if(a&&window.assetKind==='map'){let r=await sb.rpc('set_scene_map',{p_campaign_id:campaign.id,p_scene_id:scene.id,p_asset_id:a.id});if(r.error)return alert(r.error.message)}await loadWorld();broadcastRefresh();e.target.value=''};
$$('[data-library]').forEach(b=>b.onclick=()=>{libraryFilter=b.dataset.library;$$('[data-library]').forEach(x=>x.classList.toggle('active',x===b));renderAssets()});async function renderAssets(){let box=$('#assets');box.innerHTML='';let list=assets.filter(a=>libraryFilter==='token'?a.asset_type==='token'||a.asset_type==='image':a.asset_type===libraryFilter);for(let a of list){let u=await signed(a.path);box.insertAdjacentHTML('beforeend',`<div class="asset"><img src="${u}"><span>${esc(a.name)}<small>${esc(a.asset_type)}</small></span></div>`)}if(!list.length)box.innerHTML='<span class="muted">Nenhum asset nesta categoria.</span>'}
function openCampaignSettings(){if(role!=='master'||!campaign)return;$('#campaignSettingsName').value=campaign.name||'';$('#campaignSettingsDescription').value=campaign.description||'';$('#campaignSettingsRole').textContent='Mestre';$('#campaignSettingsId').textContent=campaign.id;updateCampaignCoverPreview();$('#campaignSettingsModal').classList.remove('hidden')}function closeCampaignSettings(){$('#campaignSettingsModal').classList.add('hidden')}async function updateCampaignCoverPreview(){let preview=$('#campaignCoverPreview'),u=await campaignCoverUrl(campaign);preview.style.backgroundImage=u?`linear-gradient(#0002,#0005),url('${u}')`:'';preview.innerHTML=u?'':'<span>Sem imagem</span>'}$('#campaignSettingsBtn').onclick=openCampaignSettings;$('#closeCampaignSettings').onclick=closeCampaignSettings;$$('[data-close-settings]').forEach(x=>x.onclick=closeCampaignSettings);$('#chooseCampaignCover').onclick=()=>$('#campaignCoverFile').click();
$('#campaignCoverFile').onchange=async e=>{if(role!=='master')return;let f=e.target.files[0];if(!f)return;if(f.size>8*1024*1024)return alert('A imagem deve ter no máximo 8 MB.');let ext=(f.name.split('.').pop()||'webp').replace(/[^a-zA-Z0-9]/g,''),path=`${user.id}/campaign-covers/${campaign.id}-${crypto.randomUUID()}.${ext}`;let {error}=await sb.storage.from('umbra-assets').upload(path,f,{contentType:f.type,upsert:false});if(error)return alert(error.message);let old=campaign.cover_path||null,{error:ue}=await sb.from('campaigns').update({cover_path:path,updated_at:new Date().toISOString()}).eq('id',campaign.id);if(ue)return alert(ue.message);campaign.cover_path=path;if(old)await sb.storage.from('umbra-assets').remove([old]);await updateCampaignCoverPreview();await refreshCampaignIdentity();channel?.send({type:'broadcast',event:'campaign_updated',payload:{}});e.target.value=''};$('#removeCampaignCover').onclick=async()=>{if(role!=='master'||!campaign?.cover_path)return;let old=campaign.cover_path,{error}=await sb.from('campaigns').update({cover_path:null,updated_at:new Date().toISOString()}).eq('id',campaign.id);if(error)return alert(error.message);campaign.cover_path=null;await sb.storage.from('umbra-assets').remove([old]);await updateCampaignCoverPreview();await refreshCampaignIdentity()};$('#saveCampaignSettings').onclick=async()=>{let name=$('#campaignSettingsName').value.trim(),description=$('#campaignSettingsDescription').value.trim();if(name.length<2)return alert('Informe um nome para a campanha.');let {error}=await sb.from('campaigns').update({name,description,updated_at:new Date().toISOString()}).eq('id',campaign.id);if(error)return alert(error.message);campaign.name=name;campaign.description=description;await refreshCampaignIdentity();closeCampaignSettings()};
boot();