const URL='https://weaxqjesqtkkvodwnttx.supabase.co';const KEY='sb_publishable_x4p8fV11-JMp0C5W44OKrQ_3Ug_kJw8';const sb=supabase.createClient(URL,KEY);
let user,profile,campaign,role,scene,tokens=[],fogs=[],assets=[],channel,tool='select',selected=null,drag=null,cam={x:0,y:0,z:.65};
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)]; const msg=t=>$('#authMsg').textContent=t;
async function boot(){const {data:{session}}=await sb.auth.getSession();if(session) await enter(session.user);sb.auth.onAuthStateChange(async(_,s)=>{if(s&&!user)await enter(s.user);if(!s){user=null;$('#app').classList.add('hidden');$('#auth').classList.remove('hidden')}})}
async function enter(u){user=u;let {data}=await sb.from('profiles').select('*').eq('id',u.id).single();profile=data;$('#who').textContent=profile?.display_name||u.email;$('#auth').classList.add('hidden');$('#app').classList.remove('hidden');show('home')}
$('#loginBtn').onclick=async()=>{let {error}=await sb.auth.signInWithPassword({email:$('#email').value,password:$('#password').value});msg(error?.message||'')};
$('#signupBtn').onclick=async()=>{let un=$('#username').value.trim();if(un.length<3)return msg('Informe um usuário com 3+ caracteres.');let {error}=await sb.auth.signUp({email:$('#email').value,password:$('#password').value,options:{data:{username:un,display_name:un}}});msg(error?'Erro: '+error.message:'Conta criada. Verifique seu e-mail se a confirmação estiver ativa.')};
$('#logoutBtn').onclick=()=>sb.auth.signOut(); $$('header nav button').forEach(b=>b.onclick=()=>show(b.dataset.page));
function show(p){$$('.page').forEach(x=>x.classList.add('hidden'));$('#'+p).classList.remove('hidden');if(p==='campaigns')loadCampaigns();if(p==='sheets')loadSheets()}
$('#newCampaign').onclick=async()=>{let name=prompt('Nome da campanha:');if(!name)return;let {data,error}=await sb.rpc('create_campaign',{p_name:name,p_description:''});if(error)alert(error.message);else loadCampaigns()};
async function loadCampaigns(){let {data}=await sb.from('campaigns').select('*').order('updated_at',{ascending:false});let {data:mem}=await sb.from('campaign_members').select('*');$('#campaignList').innerHTML=(data||[]).map(c=>{let r=c.owner_id===user.id?'master':mem?.find(m=>m.campaign_id===c.id&&m.user_id===user.id)?.role||'player';return `<article class="campaignCard"><h3>${esc(c.name)}</h3><p>${esc(c.description||'Sem descrição')}</p><p>${c.is_open?'🟢 Sessão aberta':'⚫ Sessão fechada'} · ${r}</p><button onclick="openCampaign('${c.id}','${r}')">${c.is_open||r==='master'?'Abrir':'Ver campanha'}</button></article>`}).join('')||'<p>Nenhuma campanha ainda.</p>'}
$('#joinBtn').onclick=async()=>{let code=$('#inviteCode').value.trim();let {error}=await sb.rpc('request_campaign_join',{p_code:code,p_role:$('#joinRole').value});alert(error?error.message:'Pedido enviado ao mestre.')};
$('#linkSheet').onclick=async()=>{let tok=prompt('Cole o token da ficha Psyque:');if(!tok)return;await sb.from('linked_sheets').insert({user_id:user.id,external_sheet_id:tok,display_name:'Ficha Psyque',status:'pending'});loadSheets()};
async function loadSheets(){let {data}=await sb.from('linked_sheets').select('*').order('created_at',{ascending:false});$('#sheetList').innerHTML=(data||[]).map(s=>`<article class="sheetCard"><h3>${esc(s.display_name)}</h3><p>Status: ${s.status}</p><small>Integração Psyque aguardando conexão do projeto externo.</small></article>`).join('')||'<p>Nenhuma ficha vinculada.</p>'}
window.openCampaign=async(id,r)=>{campaign=(await sb.from('campaigns').select('*').eq('id',id).single()).data;role=r;scene=(await sb.from('scenes').select('*').eq('campaign_id',id).order('sort_order').limit(1).single()).data;document.body.classList.remove('master','player','spectator');document.body.classList.add(role);$('#campaignName').textContent=campaign.name;$('#roleBadge').textContent=role;show('tabletop');await loadWorld();await connectRealtime();await loadSide();};
$('#backCampaigns').onclick=()=>{if(channel)sb.removeChannel(channel);show('campaigns')};
async function loadWorld(){let [t,f,a,s]=await Promise.all([sb.from('tokens').select('*').eq('scene_id',scene.id),sb.from('fog_regions').select('*').eq('scene_id',scene.id),sb.from('assets').select('*').or(`owner_id.eq.${user.id},campaign_id.eq.${campaign.id}`),sb.from('sessions').select('*').eq('campaign_id',campaign.id).eq('is_active',true).maybeSingle()]);tokens=t.data||[];fogs=f.data||[];assets=a.data||[];if(s.data)$('#rpgTime').value=s.data.rpg_time.slice(0,16);$('#rpgTime').disabled=role!=='master';$('#toggleSession').textContent=campaign.is_open?'Fechar sessão':'Abrir sessão';render()}
async function signed(path){let {data}=await sb.storage.from('umbra-assets').createSignedUrl(path,3600);return data?.signedUrl||''}
async function render(){let bg=assets.find(a=>a.id===scene.background_asset_id);$('#map').src=bg?await signed(bg.path):'';$('#fogLayer').innerHTML=fogs.map(f=>`<div class="fog" data-id="${f.id}" style="left:${f.x}px;top:${f.y}px;width:${f.width}px;height:${f.height}px;opacity:${f.opacity}"></div>`).join('');$('#tokenLayer').innerHTML='';for(let t of tokens){let el=document.createElement('div');el.className='token'+(selected===t.id?' selected':'');el.dataset.id=t.id;el.style.cssText=`left:${t.x}px;top:${t.y}px;width:${t.width}px;height:${t.height}px;transform:rotate(${t.rotation}deg)`;let a=assets.find(x=>x.id===t.image_asset_id);if(a)el.style.backgroundImage=`url("${await signed(a.path)}")`;el.innerHTML=`<span class="name">${esc(t.name)}</span>${selected===t.id&&role==='master'?'<div class="handles"><i class="handle resize"></i><i class="handle rotate"></i></div>':''}`;el.onpointerdown=e=>tokenDown(e,t);$('#tokenLayer').append(el)}applyCam();renderAssets()}
function tokenDown(e,t){if(tool!=='select'||role==='spectator')return;if(role==='player'&&(!t.player_movable||t.controller_user_id!==user.id||t.locked))return;selected=t.id;let p=worldPoint(e);drag={kind:'move',id:t.id,dx:p.x-t.x,dy:p.y-t.y};e.currentTarget.setPointerCapture(e.pointerId);render()}
$('#viewport').onpointermove=e=>{if(e.buttons===2&&channel){let p=worldPoint(e);channel.send({type:'broadcast',event:'cursor',payload:{id:user.id,name:profile.display_name,x:p.x,y:p.y,show:true}})}if(!drag)return;let t=tokens.find(x=>x.id===drag.id),p=worldPoint(e);t.x=p.x-drag.dx;t.y=p.y-drag.dy;let el=$(`.token[data-id="${t.id}"]`);if(el){el.style.left=t.x+'px';el.style.top=t.y+'px'}channel?.send({type:'broadcast',event:'token_move',payload:{id:t.id,x:t.x,y:t.y}})};
$('#viewport').onpointerup=async e=>{if(e.button===2)channel?.send({type:'broadcast',event:'cursor',payload:{id:user.id,show:false}});if(drag){let t=tokens.find(x=>x.id===drag.id);drag=null;await sb.from('tokens').update({x:t.x,y:t.y,updated_at:new Date().toISOString()}).eq('id',t.id)}};$('#viewport').oncontextmenu=e=>e.preventDefault();
function worldPoint(e){let r=$('#viewport').getBoundingClientRect();return{x:(e.clientX-r.left-cam.x)/cam.z,y:(e.clientY-r.top-cam.y)/cam.z}}
$('#viewport').onwheel=e=>{e.preventDefault();cam.z=Math.max(.2,Math.min(2,cam.z*(e.deltaY>0?.9:1.1)));applyCam()};function applyCam(){$('#world').style.transform=`translate(${cam.x}px,${cam.y}px) scale(${cam.z})`}
async function connectRealtime(){if(channel)await sb.removeChannel(channel);channel=sb.channel('campaign:'+campaign.id,{config:{broadcast:{self:false},presence:{key:user.id}}});channel.on('broadcast',{event:'token_move'},({payload:p})=>{let t=tokens.find(x=>x.id===p.id);if(t){t.x=p.x;t.y=p.y;let el=$(`.token[data-id="${p.id}"]`);if(el){el.style.left=p.x+'px';el.style.top=p.y+'px'}}}).on('broadcast',{event:'cursor'},({payload:p})=>cursor(p)).on('broadcast',{event:'refresh'},()=>loadWorld()).on('presence',{event:'sync'},()=>renderPresence());await channel.subscribe(async status=>{if(status==='SUBSCRIBED')await channel.track({name:profile.display_name,role})})}
function cursor(p){let id='c'+p.id,el=document.getElementById(id);if(!p.show){el?.remove();return}if(!el){el=document.createElement('div');el.id=id;el.className='cursorDot';el.innerHTML=`<span>${esc(p.name||'Jogador')}</span>`;$('#cursorLayer').append(el)}el.style.left=p.x+'px';el.style.top=p.y+'px'}function renderPresence(){let st=channel?.presenceState()||{};$('#members').innerHTML=Object.values(st).flat().map(x=>`<div>● ${esc(x.name)} <small>${x.role}</small></div>`).join('')}
$$('[data-tool]').forEach(b=>b.onclick=()=>tool=b.dataset.tool);$('#viewport').onpointerdown=async e=>{if(role!=='master'||e.target.closest('.token'))return;if(tool==='fog'||tool==='fogOpacity'){let p=worldPoint(e),start=p;let box=$('#selectionBox');box.style.display='block';let move=ev=>{let q=worldPoint(ev),x=Math.min(start.x,q.x),y=Math.min(start.y,q.y),w=Math.abs(q.x-start.x),h=Math.abs(q.y-start.y);Object.assign(box.style,{left:x+'px',top:y+'px',width:w+'px',height:h+'px'})};let up=async ev=>{window.removeEventListener('pointermove',move);window.removeEventListener('pointerup',up);box.style.display='none';let q=worldPoint(ev),x=Math.min(start.x,q.x),y=Math.min(start.y,q.y),w=Math.abs(q.x-start.x),h=Math.abs(q.y-start.y);if(w<5||h<5)return;if(tool==='fog'){await sb.from('fog_regions').insert({campaign_id:campaign.id,scene_id:scene.id,x,y,width:w,height:h,opacity:1})}else{let op=Number(prompt('Opacidade de 0 a 100:',50))/100;for(let f of fogs.filter(f=>!(f.x+f.width<x||f.x>x+w||f.y+f.height<y||f.y>y+h)))await sb.from('fog_regions').update({opacity:Math.max(0,Math.min(1,op))}).eq('id',f.id)}await loadWorld();channel.send({type:'broadcast',event:'refresh',payload:{}})};window.addEventListener('pointermove',move);window.addEventListener('pointerup',up)}};
$('#addToken').onclick=async()=>{let name=prompt('Nome do token:','Novo token');if(!name)return;await sb.from('tokens').insert({campaign_id:campaign.id,scene_id:scene.id,name,x:500,y:350,player_movable:false});await loadWorld();channel.send({type:'broadcast',event:'refresh',payload:{}})};
$('#addMap').onclick=()=>{window.assetKind='map';$('#assetFile').click()};$('#assetFile').onchange=async e=>{let f=e.target.files[0];if(!f)return;let path=`${user.id}/${crypto.randomUUID()}-${f.name.replace(/[^a-zA-Z0-9._-]/g,'_')}`;let {error}=await sb.storage.from('umbra-assets').upload(path,f);if(error)return alert(error.message);let {data:a,error:ae}=await sb.from('assets').insert({owner_id:user.id,campaign_id:campaign.id,path,name:f.name,asset_type:window.assetKind||'image',mime_type:f.type,size_bytes:f.size}).select().single();if(a&&window.assetKind==='map')await sb.from('scenes').update({background_asset_id:a.id}).eq('id',scene.id);await loadWorld();channel.send({type:'broadcast',event:'refresh',payload:{}});e.target.value=''};
async function renderAssets(){$('#assets').innerHTML='';for(let a of assets.filter(x=>x.owner_id===user.id)){let u=await signed(a.path);$('#assets').insertAdjacentHTML('beforeend',`<div class="asset"><img src="${u}"><span>${esc(a.name)}<br><small>${a.asset_type}</small></span></div>`)}}
async function loadSide(){if(role!=='master')return;let {data:req}=await sb.from('campaign_join_requests').select('*,profiles!campaign_join_requests_requester_id_fkey(display_name)').eq('campaign_id',campaign.id).eq('status','pending');$('#requests').innerHTML=(req||[]).map(r=>`<div class="request">${esc(r.profiles?.display_name||'Usuário')} quer entrar como ${r.requested_role}<br><button onclick="resolveReq('${r.id}',true)">Aceitar</button><button onclick="resolveReq('${r.id}',false)" class="ghost">Recusar</button></div>`).join('');}
window.resolveReq=async(id,ok)=>{await sb.rpc('resolve_join_request',{p_request_id:id,p_accept:ok});loadSide()};
$('#toggleSession').onclick=async()=>{if(role!=='master')return;await sb.rpc('set_campaign_open',{p_campaign_id:campaign.id,p_open:!campaign.is_open});campaign.is_open=!campaign.is_open;$('#toggleSession').textContent=campaign.is_open?'Fechar sessão':'Abrir sessão'};$('#rpgTime').onchange=async()=>{if(role==='master')await sb.rpc('set_rpg_time',{p_campaign_id:campaign.id,p_time:$('#rpgTime').value})};
function esc(s){return String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}boot();